---
title: "Eksploratorna analiza Catan dataseta"
author: "Vedran Knežević, Andrej Lovei"
date: "2024-01-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(stringr)
```

# Uvod

Za početak treba učitati dataset i pogledati koje se sve varijable unutra nalaze.

```{r eval=FALSE}
data <- read_csv("../data/SettlersOfCatanStats.csv")
```

```{r}
glimpse(data)
```

Vidimo da postoje varijable koje bi se ili mogle izbaciti ili faktorirati. Kao varijabla me, gdje autor dataseta bilježi radi li se u tom retku tablice o njemu (smatramo da to nama nije bitno pa možemo ignorirati). A za varijable tipa ...broj, njih bi valjalo preimenovati.


```{r}
data$me <- NULL

names(data)[names(data) == "settlement1"] <- "startNum1"
names(data)[names(data) == "...17"] <- "startRes1"
names(data)[names(data) == "...18"] <- "startNum2"
names(data)[names(data) == "...19"] <- "startRes2"
names(data)[names(data) == "...20"] <- "startNum3"
names(data)[names(data) == "...21"] <- "startRes3"

names(data)[names(data) == "settlement2"] <- "startNum4"
names(data)[names(data) == "...23"] <- "startRes4"
names(data)[names(data) == "...24"] <- "startNum5"
names(data)[names(data) == "...25"] <- "startRes5"
names(data)[names(data) == "...27"] <- "startNum6"

data$won <- ifelse(data$points >= 10, 1, 0)
data$won <- factor(data$won, levels = c(0, 1), labels = c(FALSE, TRUE))
```


